---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/b2c":
    post:
      summary: b2c_transaction
      responses:
        "200":
          description: successful
  "/payment_query":
    post:
      summary: stkquery callback
      responses:
        "200":
          description: successful
  "/callback":
    post:
      summary: mpesa_callback callback
      responses:
        "200":
          description: successful
  "/pay":
    post:
      summary: stkpush mpesa
      responses:
        "200":
          description: successful
servers:
  - url: https://{defaultHost}
    variables:
      defaultHost:
        default: www.example.com
