MPESA_CONSUMER_KEY: "7kdGlWglUky9GQiuXEgDnE6ghTVyCSeagqpLK9qM6cEGBklu"
MPESA_CONSUMER_SECRET: "uryKJwPFqaDoq3Am0ACxqPGRmd3MOirYjJ52nAIfAUT3FCoAqDOofmCjFFFvzg4O"
MPESA_PASSKEY: "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
MPESA_SHORTCODE: "174379"
MPESA_INITIATOR_NAME: "testapi"
MPESA_INITIATOR_PASSWORD: "Safaricom999!*!"
CALLBACK_URL: "https://mn20qvr9-3000.uks1.devtunnels.ms"
REGISTER_URL: "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"
